### PR TITLE
First draft of p:http-request

### PR DESCRIPTION
**Pull request by xml-project**
Please find here the first draft on p:http-request which is to replace the existing text comming from the 1.0 specs.
@ndw @xatapult @Gertone @gimsieke 
"Edit from maintainers" is on, so feel free to make changes.

### CODE REVIEW

**Comment by xatapult** [comment]
Is there a build where we can look at the formatted result somewhere?

And there are no reviewers mentioned. Intentional or oversight?

**Comment by xml-project** [comment]
> Is there a build where we can look at the formatted result somewhere?

Send you a mail this afternoon.

> And there are no reviewers mentioned. Intentional or oversight?

As it is not finished, I did not want to ask for a review because I am not sure, we want to merge it in this state. Any opinion?

**Comment by xatapult** [comment]
Probably the devil is in the details, but this looks very OK to me. It reflects (as far as I remember) what we spoke about in Cologne and later.

**Comment by ndw** [comment]
I thought there were some changes proposed at our editor's call. I think it makes sense to make those changes and make another editorial pass.

**Comment by xml-project** [comment]
@ndw I thought I did make the requested changes from editors call. What did I left out?

**Comment by xatapult** [comment]
I took the liberty to change some words and grammar without changing meaning.

**Comment by xatapult** [comment]
The description of the `serialization` option differs. 

* The introduction mentions that the `serialization` property is ignored when more than one document appears on the source port
* Later on it says that the `serialization` property is used for all documents on the source port

**Comment by xatapult** [comment]
Urgh. What did I do to make the build fail? Can't make sense of the Travis generated error message

**Comment by xml-project** [comment]
@xatapult Oh, left that out.

**Comment by ndw** [comment]
At a glance, @xatapult you've made steps/http-request.xml not well-formed XML or not valid DocBook.

**Comment by xml-project** [comment]
Not sure what happend, but now I am out on my own PR. Trying to push something to my repo's branch git says, I had to merge Erik changes first. No idea what that means.
Let's see if it goes away once travis passes.

**Comment by xml-project** [comment]
@xatapult 
> Urgh. What did I do to make the build fail? Can't make sense of the Travis generated error message

It is in line 131: a </error> close is missing.

**Comment by xatapult** [comment]
Maybe we should limit the discussion(s) about http-request to a single issue. You now mention several. So I suggest to close all except one (or all and open a new one especially for finishing http-request)

**Pull request merged**
