### PR TITLE
First draft to fix 403

### PR DESCRIPTION
**Pull request by xml-project**
This is a first draft of my ideas on how to make p:os-exec more XProc 3.0 like.
Will add the entry to the change log as soon as this gets approved. Not sure whether it would interfere with other PRs if I do it now.

### CODE REVIEW

**Comment by xml-project** [comment]
Because I made many changes, a rendering might help: Please find it [here](https://xml-project.com/files/temp/os/)

**Comment by xatapult** [comment]
It looks very good to me. For the use-case I have it would be more than sufficient. 

One small enhancement maybe: Define a default value of `<p:empty>`  for the `source` port?

**Comment by cmarchand** [comment]
This sounds good to me, at least for the use-cases I have. For example an scp command...
And it's much more understandable than the [previous one](https://spec.xproc.org/master/head/os/#c.os-exec) !

**Comment by xml-project** [comment]
@ndw @gimsieke Any objection to merging this and then sort out the minor questions about option naming?

**Comment by xml-project** [comment]
@gimsieke Thanks for finding this. I just changed the section on p:os-exec, so I did not look at the rest.
Are we sure that we will not add additional steps to this library. If so and those steps raise errors, we would have to change it back again.
Suggestion: Leave it as section 4, but change singular to plural. Does that make sense?

**Comment by gimsieke** [comment]
Yes, of course.

**Pull request merged**
