### PR TITLE
Attempt to resolve 253

### PR DESCRIPTION
**Pull request by eriksiegel**
Editorial update on the file steps. #253

### CODE REVIEW

**Comment by eriksiegel** [comment]
@gimsieke No I wasn't aware of that list, thanks 👍 . Since it is manually maintained, is it up to date do you think?

I'll change the error codes to new ones, no problem.

**Comment by eriksiegel** [comment]
@gimsieke, would you mind to review again?

**Comment by gimsieke** [comment]
Until [Aug 5](https://github.com/xproc/3.0-steps/pull/185#pullrequestreview-270584897) I wasn’t aware of the list either…
Before that, Norm and Achim have maintained in secret for about two years!

**Comment by xml-project** [comment]
> Before that, Norm and Achim have maintained in secret for about two years!

No we have not. It would be a very stupid thing to keep a list secret _**in a public wiki**_, wouldn't it?

**Comment by gimsieke** [comment]
> 
> 
> > Before that, Norm and Achim have maintained in secret for about two years!
> 
> No we have not. It would be a very stupid thing to keep a list secret _**in a public wiki**_, wouldn't it?

If you have co-editors like Erik and me, apparently you can!

**Pull request merged**
