### PR TITLE
Issue #470: Clarify p:unwrap for empty elements

### PR DESCRIPTION
**Pull request by xatapult**

### CODE REVIEW

**Comment by ndw** [comment]
There's no such thing as an "empty text node", perhaps:

> &lt;para>This step produces a single document; if the document element is
unwrapped, the result might not be well-formed XML. If the document
element is empty or contains a single text node child, the result will
have the content type “&lt;literal>text/plain&lt;/literal>”. If the document
element is empty, the resulting document will be empty.&lt;/para>

**Comment by xatapult** [comment]
Now I'm getting confused. I thought we decided that unwrapping an empty element would produce:

* A document node with
* A single text node child containing the empty string

Is this not correct?

**Comment by gimsieke** [comment]
No, as Norm said above and I said in [#470](https://github.com/xproc/3.0-steps/issues/470#issuecomment-711756096), there is no such thing as an empty text node. As Norm suggested, when the unwrapped element doesn’t contain a node, the result will be an empty text document, that is, a document node with `content-type=text/plain` and no child nodes.

**Comment by xatapult** [comment]
All right, I'll try to reformulate

**Comment by xatapult** [comment]
Changed the last paragraph into a list and reformulated it a bit. Could you please check again?

**Comment by gimsieke** [comment]
Shouldn’t we change the sentence “All document properties are preserved” to “With the exception of the special cases where `content-type` is changed to `text/plain` and a possible `serialization` property is removed, all document properties are preserved.”? Otherwise Ok!

**Comment by xatapult** [comment]
@ndw Are you ok with Gerrit's suggestion?

**Comment by ndw** [comment]
I'm ok with Gerrit's suggestion.

**Comment by xatapult** [comment]
@ndw and/or @gimsieke I rephrased some sentences, to make it as clear as possible, so that even I can understand what's happening 😉 

Would you mind checking again?

**Review by gimsieke — APPROVED** [review]

**Pull request merged**
