### PR TITLE
Attempt to fix 567

### PR DESCRIPTION
**Pull request by xml-project**
Renaming C0201 -> C0206 and C0202->C0207

### CODE REVIEW

**Review by ndw — APPROVED** [review]

**Comment by xml-project** [comment]
@ndw @gimsieke @xatapult 
What is the politics about merging here? Merge or wait for bulk action?
close #567

**Comment by ndw** [comment]
That's a good question. Let's leave it for the moment. I should try to pull together new drafts that identify the errata.

**Comment by xml-project** [comment]
@ndw Ok. A quick check showed that 8 tests in the test suite are related to this PR. I will file a PR for these later.

**Comment by xml-project** [comment]
Remember to merge https://github.com/xproc/3.0-test-suite/pull/709 once this is merged.

**Comment by ndw** [comment]
I'm going to merge this, I'm trying to tidy things up for next week.

**Pull request merged**
